### ISSUE TITLE
[一般]租户管理->资源配额审批界面，点击资源区域后的文本框，界面显示异常

### ISSUE THREAD

**Issue by xiexm** [AIPaaS/PaaS-FE-Platform-MGMT#1]
环境win7
浏览器：火狐
测试环境：
管理门户：http://10.1.245.248:16002/paas-console
[概要]：租户管理->资源配额审批界面，点击资源区域后的文本框，界面显示异常
[详细步骤]：
1.管理门户登录test/123456
2.租户管理->租户管理->资源配额审批界面，点击资源区域后的文本框，界面显示异常
[实际结果]：
界面显示异常
[预期结果]:
界面显示正常。
[重现率]:100%
@wanwb @renfeng3

**Comment by wanwb** [comment]
已修改

**Comment by xiexm** [comment]
验证通过。
